export const jungleAssets = {
  scene1: '/assets/jungle%20/scene/scene1.png',
  scene2: '/assets/jungle%20/scene/scene2.png',
  scene3: '/assets/jungle%20/scene/scene3.png',
  scene4: '/assets/jungle%20/scene/scene4.png',
  scene5: '/assets/jungle%20/scene/scene5.png',
  scene6: '/assets/jungle%20/scene/scene6.png',
  scene7: '/assets/jungle%20/scene/scene7.png',
  butterfly: '/assets/jungle%20/entities/butterfly.png',
  ladybug: '/assets/jungle%20/entities/lady%20bug.png',
  ants: '/assets/jungle%20/entities/ant.png',
  mushroom: '/assets/jungle%20/entities/mushroom.png',
  tree: '/assets/jungle%20/entities/tree.png',
  monkey: '/assets/jungle%20/entities/Monkey.png',
  parrot: '/assets/jungle%20/entities/parrot.png',
  toucan: '/assets/jungle%20/entities/tucon.png',
  turtle: '/assets/jungle%20/entities/turtle.png',
  frog: '/assets/jungle%20/entities/frog.png',
  lily: '/assets/jungle%20/entities/lily.png',
  elephant: '/assets/jungle%20/entities/elephant.png',
  waterfall: '/assets/jungle%20/entities/waterfall.png',
  redFlower: '/assets/jungle%20/entities/red%20flower.png',
} as const;
