import { jungleAssets } from '@/lib/jungle/assets';
import type { JungleSceneDefinition, JungleSceneId } from '@/lib/jungle/types';

export const jungleScenes: Record<JungleSceneId, JungleSceneDefinition> = {
  scene1: {
    id: 'scene1',
    name: 'Jungle Entrance',
    image: jungleAssets.scene1,
    nextSceneId: 'scene2',
    hotspots: [
      {
        id: 'scene1-butterfly',
        label: 'Flutter the Butterfly',
        type: 'entity',
        entityId: 'flutter-butterfly',
        x: 38,
        y: 22,
        width: 6,
        height: 9,
        rounded: '999px',
      },
      {
        id: 'scene1-next',
        label: 'Go to Forest Trail',
        type: 'navigation',
        targetScene: 'scene2',
        x: 40,
        y: 79,
        width: 20,
        height: 17,
        rounded: '999px',
      },
    ],
  },
  scene2: {
    id: 'scene2',
    name: 'Forest Trail',
    image: jungleAssets.scene2,
    nextSceneId: 'scene3',
    hotspots: [
      {
        id: 'scene2-ladybug',
        label: 'Dot the Ladybug',
        type: 'entity',
        entityId: 'dot-ladybug',
        x: 2,
        y: 68,
        width: 12,
        height: 14,
        rounded: '999px',
      },
      {
        id: 'scene2-mushroom',
        label: 'Milo the Mushroom',
        type: 'entity',
        entityId: 'milo-mushroom',
        x: 0,
        y: 46,
        width: 21,
        height: 28,
        rounded: '24px',
      },
      {
        id: 'scene2-ants',
        label: 'Andy and the Ants',
        type: 'entity',
        entityId: 'andy-ants',
        x: 44,
        y: 67,
        width: 27,
        height: 16,
        rounded: '24px',
      },
      {
        id: 'scene2-next',
        label: 'Go to Ancient Tree',
        type: 'navigation',
        targetScene: 'scene3',
        x: 40,
        y: 79,
        width: 20,
        height: 17,
        rounded: '999px',
      },
    ],
  },
  scene3: {
    id: 'scene3',
    name: 'Ancient Tree',
    image: jungleAssets.scene3,
    nextSceneId: 'scene4',
    hotspots: [
      {
        id: 'scene3-tree',
        label: 'Tiko the Ancient Tree',
        type: 'entity',
        entityId: 'tiko-ancient-tree',
        x: 31,
        y: 0,
        width: 61,
        height: 91,
        rounded: '32px',
      },
      {
        id: 'scene3-monkey',
        label: 'Momo the Monkey',
        type: 'entity',
        entityId: 'momo-monkey',
        x: 28,
        y: 12,
        width: 13,
        height: 28,
        rounded: '999px',
      },
      {
        id: 'scene3-next',
        label: 'Go to Tree Canopy',
        type: 'navigation',
        targetScene: 'scene4',
        x: 40,
        y: 79,
        width: 20,
        height: 17,
        rounded: '999px',
      },
    ],
  },
  scene4: {
    id: 'scene4',
    name: 'Tree Canopy',
    image: jungleAssets.scene4,
    nextSceneId: 'scene5',
    hotspots: [
      {
        id: 'scene4-toucan',
        label: 'Tuki the Toucan',
        type: 'entity',
        entityId: 'tuki-toucan',
        x: 0,
        y: 12,
        width: 18,
        height: 30,
        rounded: '999px',
      },
      {
        id: 'scene4-parrot',
        label: 'Pico the Parrot',
        type: 'entity',
        entityId: 'pico-parrot',
        x: 82,
        y: 7,
        width: 18,
        height: 41,
        rounded: '999px',
      },
      {
        id: 'scene4-next',
        label: 'Go to Jungle River',
        type: 'navigation',
        targetScene: 'scene5',
        x: 40,
        y: 79,
        width: 20,
        height: 17,
        rounded: '999px',
      },
    ],
  },
  scene5: {
    id: 'scene5',
    name: 'Jungle River',
    image: jungleAssets.scene5,
    nextSceneId: 'scene6',
    hotspots: [
      {
        id: 'scene5-lily',
        label: 'Lulu the Water Lily',
        type: 'entity',
        entityId: 'lulu-water-lily',
        x: 18,
        y: 44,
        width: 28,
        height: 23,
        rounded: '32px',
      },
      {
        id: 'scene5-frog',
        label: 'Freddie the Frog',
        type: 'entity',
        entityId: 'freddie-frog',
        x: 3,
        y: 64,
        width: 18,
        height: 23,
        rounded: '999px',
      },
      {
        id: 'scene5-turtle',
        label: 'Tilly the Turtle',
        type: 'entity',
        entityId: 'tilly-turtle-jungle',
        x: 62,
        y: 48,
        width: 25,
        height: 28,
        rounded: '32px',
      },
      {
        id: 'scene5-next',
        label: 'Go to Watering Hole',
        type: 'navigation',
        targetScene: 'scene6',
        x: 40,
        y: 79,
        width: 20,
        height: 17,
        rounded: '999px',
      },
    ],
  },
  scene6: {
    id: 'scene6',
    name: 'Watering Hole',
    image: jungleAssets.scene6,
    nextSceneId: 'scene7',
    hotspots: [
      {
        id: 'scene6-elephant',
        label: 'Ellie the Elephant',
        type: 'entity',
        entityId: 'ellie-elephant',
        x: 45,
        y: 17,
        width: 47,
        height: 54,
        rounded: '32px',
      },
      {
        id: 'scene6-next',
        label: 'Go to Hidden Waterfall',
        type: 'navigation',
        targetScene: 'scene7',
        x: 40,
        y: 79,
        width: 20,
        height: 17,
        rounded: '999px',
      },
    ],
  },
  scene7: {
    id: 'scene7',
    name: 'Hidden Waterfall',
    image: jungleAssets.scene7,
    hotspots: [
      {
        id: 'scene7-waterfall',
        label: 'Wally the Waterfall',
        type: 'entity',
        entityId: 'wally-waterfall',
        x: 26,
        y: 0,
        width: 49,
        height: 63,
        rounded: '32px',
      },
      {
        id: 'scene7-red-flower-left',
        label: 'Ruby the Hibiscus',
        type: 'entity',
        entityId: 'ruby-red-flower',
        x: 0,
        y: 63,
        width: 15,
        height: 25,
        rounded: '999px',
      },
      {
        id: 'scene7-red-flower-right',
        label: 'Ruby the Hibiscus',
        type: 'entity',
        entityId: 'ruby-red-flower',
        x: 79,
        y: 45,
        width: 18,
        height: 34,
        rounded: '999px',
      },
    ],
  },
};
